Update Golang to v1.22
nestybox/sysbox-libs pull request #54
Opened 2024-10-06 04:29 UTC by rodnymolina

2024-10-06 20:38 UTC, ctalledo requested changes

2024-10-06 20:38 UTC, ctalledo commented on overlayUtils/go.mod
>  go 1.21
Doesn't this need to be v1.22?

2024-10-07 06:09 UTC, rodnymolina commented on overlayUtils/go.mod
>  go 1.21
done

2024-10-07 16:09 UTC, ctalledo approved these changes
LGTM ... thanks!

2024-10-07 18:30 UTC, merged